name: Test
on:
  push:
  pull_request:
permissions:
  contents: read
concurrency:
  group: windows-chrome-${{ github.event.pull_request.head.ref || github.ref_name }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: windows-latest
    timeout-minutes: 8
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/windows-build
